apiVersion: v1
kind: Service
metadata:
  name: stock-ai-backend
  labels:
    app.kubernetes.io/name: stock-ai-backend
spec:
  selector:
    app.kubernetes.io/name: stock-ai-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
