apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stock-ai-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stock-ai-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stock-ai-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stock-ai-frontend
