apiVersion: v1
kind: Service
metadata:
  name: stock-ai-frontend
  labels:
    app.kubernetes.io/name: stock-ai-frontend
spec:
  selector:
    app.kubernetes.io/name: stock-ai-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
